name: Run Web Scraping Manually

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub
  push:
    branches:
      - 'master'

jobs:
  run_scraping_manually:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run web scraping script
        id: scraping
        env:
          PREVIOUS_STATUS: ${{ vars.PREVIOUS_STATUS }}
        run: |
          python scripts/core.py
          echo "${{ env.IS_CHANGE_VERSION }}"
          echo "${{ vars.IS_CHANGE_VERSION }}"
          echo $IS_CHANGE_VERSION
          echo ${IS_CHANGE_VERSION}
          echo "\n"
          echo "${{ env.STATUS_MESSAGE_TEXT }}"
          echo "${{ vars.STATUS_MESSAGE_TEXT }}"
          echo $STATUS_MESSAGE_TEXT
          echo ${STATUS_MESSAGE_TEXT}

      - name: Send WhatsApp message
        if: ${{ vars.PREVIOUS_STATUS }} != ''
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          WHATSAPP_PHONE_NUMBER: ${{ secrets.WHATSAPP_PHONE_NUMBER }}
          MESSAGE: ${{ env.STATUS_MESSAGE_TEXT }}
        run: |
          echo "${{ env.IS_CHANGE_VERSION }}"
          echo "${{ env.STATUS_MESSAGE_TEXT }}"

        #run: python scripts/send_whatsapp_message.py  # Asegúrate de que esta ruta sea correcta en relación con tu repositorio
