name: Run Web Scraping Manually

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run web scraping script
        run: python core.py
