name: Run Web Scraping Manually

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  run_scraping_manually:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run web scraping script
        id: scraping
        env:
          PREVIOUS_STATUS: ${{ vars.PREVIOUS_STATUS }}
        run:
          echo "CURRENT_STATUS=$(python scripts/core.py)" >> $GITHUB_ENV

      # Añade un paso para enviar el mensaje de WhatsApp
      - name: Send WhatsApp message
        if: ${{ vars.PREVIOUS_STATUS }} =! ${{ env.CURRENT_STATUS }}
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          WHATSAPP_PHONE_NUMBER: ${{ secrets.WHATSAPP_PHONE_NUMBER }}
          MESSAGE: '''
          La versión ha cambiado: 
          *Versión anterior:* ${{ env.PREVIOUS_STATUS }}
          *Versión actual:* ${{ env.CURRENT_STATUS }}
          '''
        run: python scripts/send_whatsapp_message.py  # Asegúrate de que esta ruta sea correcta en relación con tu repositorio
