name: Send email

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  run_scraping_manually:
    runs-on: ubuntu-latest

    steps:
          - name: Send mail
            uses: dawidd6/action-send-mail@v3
            with:
              server_address: smtp.gmail.com
              server_port: 465
              secure: true
              subject: Github Actions job result
              to: nico2361993@gmail.com
              from: nico2361993@gmail.com
              body: Build job of ${{github.repository}} completed successfully!
              nodemailerdebug: false