name: Send Random WhatsApp Message

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt'

      - name: Generate random message
        id: random_message
        run: |
          echo "message=$(python -c 'import random; messages = ["¡Hola!", "¡Buenos días!", "¿Cómo estás?", "¡Feliz día!"]; print(random.choice(messages))')" >> $GITHUB_ENV

      - name: Send WhatsApp message
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          WHATSAPP_PHONE_NUMBER: ${{ secrets.WHATSAPP_PHONE_NUMBER }}
          MESSAGE: ${{ env.message }}
        run: python scripts/send_whatsapp_message.py
