name: Send Random WhatsApp Message

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Generate random message
        id: random_message
        run: echo "::set-output name=message::$(python -c "import random; messages = ['¡Hola!', '¡Buenos días!', '¿Cómo estás?', '¡Feliz día!']; print(random.choice(messages))")"

      - name: Send WhatsApp message
        uses: 403-html/whatsapp-action@v2
        with:
          twilio_account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          twilio_auth_token: ${{ secrets.TWILIO_AUTH_TOKEN }}
          twilio_from_number: ${{ secrets.TWILIO_PHONE_NUMBER }}
          to: "whatsapp:${{ secrets.WHATSAPP_PHONE_NUMBER }}"
          body: ${{ steps.random_message.outputs.message }}
