name: Send Random WhatsApp Message

on:
  workflow_dispatch: # Permitir ejecución manual desde la interfaz de GitHub

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
      - name: Generate random message
        id: random_message
        run: |
          echo "message=$(python -c 'import random; messages = ["¡Hola!", "¡Buenos días!", "¿Cómo estás?", "¡Feliz día!"]; print(random.choice(messages))')" >> $GITHUB_ENV
      # Añade un paso para enviar el mensaje de WhatsApp
      - name: Send WhatsApp message
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          WHATSAPP_PHONE_NUMBER: ${{ secrets.WHATSAPP_PHONE_NUMBER }}
          MESSAGE: ${{ env.message }}
        run: python scripts/send_whatsapp_message.py  # Asegúrate de que esta ruta sea correcta en relación con tu repositorio
